강의/JS/06_JS_with_django/06_JS_with_django/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
    path('profile/<username>/', views.profile, name='profile'),
    # path('profile/<str:username>/')
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

강의/JS/06_JS_with_django/06_JS_with_django/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

강의/JS/06_JS_with_django/06_JS_with_django/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

강의/JS/06_JS_with_django/06_JS_with_django/articles/models.py
from django.db import models
# from accounts.models import User
# from django.contrib.auth import get_user_model
from django.conf import settings


# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

강의/JS/06_JS_with_django/06_JS_with_django/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            'email',
            'first_name',
            'last_name',
        )

강의/JS/06_JS_with_django/06_JS_with_django/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from .forms import CustomUserCreationForm, CustomUserChangeForm


# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')

    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('articles:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request):
    request.user.delete()
    return redirect('articles:index')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/password.html', context)

# 프로필 페이지를 제공
from django.contrib.auth import get_user_model


def profile(request, username):
    # 해당 프로필 페이지의 유저를 조회
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)

from django.http import JsonResponse

@login_required
def follow(request, user_pk):
    User = get_user_model()

    person = User.objects.get(pk=user_pk)
    if person != request.user:
        if person.followers.filter(pk=request.user.pk).exists():
            person.followers.remove(request.user)
            is_followed = False
        else:
            person.followers.add(request.user)
            is_followed = True
        context = {
            'is_followed': is_followed,
            'followings_count': person.followings.count(),
            'followers_count': person.followers.count()
        }
        return JsonResponse(context)
    return redirect('accounts:profile', person.username)

강의/JS/06_JS_with_django/06_JS_with_django/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>로그인</h1>
  <form action="{% url "accounts:login" %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
  </form>
</body>
</html>

강의/JS/06_JS_with_django/06_JS_with_django/accounts/templates/accounts/password.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>비밀번호 변경</h1>
  <form action="{% url "accounts:password" %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
  </form>
</body>
</html>

강의/JS/06_JS_with_django/06_JS_with_django/accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>{{ person.username }}님의 프로필</h1>
  <div>
    팔로워 : <span id='followers-count'>{{ person.followers.all|length }}</span> / 
    팔로우 : <span id='followings-count'>{{ person.followings.all|length }} </span>
  </div>

  {% if request.user != person %}
    <form action="{% url "accounts:follow" person.pk %}" method="POST" id="follow-form" data-user-id="{{ person.pk }}"> 
      {% csrf_token %}
      {% if request.user in person.followers.all %}
        <input type="submit" value='UnFollow'>
      {% else %}
        <input type="submit" value='Follow'>
      {% endif %}
    </form>
  {% endif %}
  <hr>

  {% comment %} 게시글 {% endcomment %}
  <h2>{{ person.username }} 작성한 게시글</h2>
  {% for article in person.article_set.all %}
    <div>{{ article.title }}</div>
  {% endfor %}
  <hr>

  {% comment %} 댓글 {% endcomment %}
  <h2>{{ person.username }} 작성한 댓글</h2>
  {% for comment in person.comment_set.all %}
    <div>{{ comment.content }}</div>
  {% endfor %}
  <hr>

  {% comment %} 좋아요 한 게시글 {% endcomment %}
  <h2>{{ person.username }} 좋아요 한 게시글</h2>
  {% for article in person.like_articles.all %}
    <div>{{ article.title }}</div>
  {% endfor %}

  <!-- HTML 콘텐츠를 모두 사용자에게 보여준 후에 스크립트를 다운로드하고 실행 -->
  <!-- 사실 그렇게 차이는 없음 -->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    // 1. 선택자를 활용해서 html 요소 가져오기 
    const formTag = document.querySelector('#follow-form')
    // 2. 폼을 제출했을 때 => 새로고침을 막고, axios를 활용해서 비동기적으로 좋아요를 진행 
    formTag.addEventListener('submit', function (event){
      // 새로고침 중단
      event.preventDefault()
      
      // 방법1. event.currentTarget: 이벤트 리스너가 부착된 요소(formTag)
      // 가장 명시적이고 안정적인 방법
      // (가장 추천, 누가 봐도 이벤트, 화살표 함수와의 호환 )
      const userId = event.currentTarget.dataset.userId
      // 방법2. 일반 함수이기 때문에 이벤트 리스너가 부착된 요소를 가리킴
      // 화살표 함수를 사용하면 this가 formTag를 가리키지 않기 때문에 주의 
      // const userId = this.dataset.userId

      // 방법3. 직관적이고, 화살표함수도 문제가 없지만 
      // 이벤트 핸들러가 formTag에 접근할 수 있는 스코프여야 함 
      // const userId = formTag.dataset.userId

      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
      // 팔로우/언팔로우 조작 시 필요한 데이터는 ?
      // 1. 조작하고 싶은 유저의 pk
      // 2. POST 메서드이기 때문에 csrf_token을 보내야 함 
      axios({
        method: 'POST',  // 팔로우/언팔로우 하면서 데이터를 조작하기 때문에 POST 메서드 
        url: `/accounts/${userId}/follow/`,  // 버튼을 누르면 해당 url 에 요청 
        headers: {'X-CSRFToken': csrftoken},
      }).then((response) => {
        const isFollowed = response.data.is_followed
        const followBtn = document.querySelector('input[type=submit]')
        const followingsCountTag = document.querySelector('#followings-count')
        const followersCountTag = document.querySelector('#followers-count')

        if (isFollowed === true) {
          followBtn.value = 'UnFollow'
        } else {
          followBtn.value = 'Follow'
        }
        
        followingsCountTag.textContent = response.data.followings_count
        followersCountTag.textContent = response.data.followers_count
      })
    })
  </script>
</body>
</html>

강의/JS/06_JS_with_django/06_JS_with_django/accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>회원가입</h1>
  <form action="{% url "accounts:signup" %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
  </form>
</body>
</html>

강의/JS/06_JS_with_django/06_JS_with_django/accounts/templates/accounts/update.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>회원정보수정</h1>
  <form action="{% url "accounts:update" %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
  </form>
</body>
</html>